[theme]
base="light"
primaryColor="#8e00c6"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#f0daf2"
textColor="#000000"
font="sans serif"

[ui]
hideTopBar = true

[server]
enableCORS = false
enableXsrfProtection = false
runOnSave = false


