[theme]
base="light"
primaryColor="#ED0779"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#fadbe6"
textColor="#000000"
font="sans serif"

[ui]
hideTopBar = true

[runner]
fastReruns = true

[server]
enableCORS = false
enableXsrfProtection = false
runOnSave = false
headless = true
enableStaticServing = true


[client]
showSidebarNavigation = false